### ISSUE TITLE
XML (DOMDocument) support on Synology

### ISSUE THREAD

**Issue by razvanioan** [MaRmARk0/Synology-DownloadStation-Hosts-CZ-SK#1]
I am also writing a DLM module for one site I preffer, and I have to parse their search result pages as they do not share any kind of API, but I don't think that DOMDocument is supported by default on Synology's Apache / PHP as I cannot use it.

Maybe you have IPKG installed with different Apache / PHP.

**Comment by MaRmARk0** [comment]
Hi there. I've just checked my DS213j (DSM 5.1-5022). I have Apache/2.2.29, PHP/5.5.19 (Zend Engine 2.50, Zend OPcache 7.04-dev). Part of my phpinfo() 

```ini
dom

DOM/XML => enabled
DOM/XML API Version => 20031129
libxml Version => 2.9.1
HTML Support => enabled
XPath Support => enabled
XPointer Support => enabled
Schema Support => enabled
RelaxNG Support => enabled

libxml

libXML support => active
libXML Compiled Version => 2.9.1
libXML Loaded Version => 20901-GITCMS-1.0-0270-140422-4-g50ceccc
libXML streams => enabled

```

I think you could use XPath instead of DOMDocument to traverse DOM.

**Comment by razvanioan** [comment]
Yes, you are right !

I also have them enabled (just checked).

I don't know from my DownloadStation script it stops at the line where I define new DOMDocument() ... I thought they were not active (my bad that I didn't check before)

Thx,
